[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "salesforcesdkjs"
description = "Receives a payload containing account details, and creates the record. It then uses a SOQL query to return the newly created Account."
type = "function"
